[package]
name = "lab5-final"
version = "0.1.0"
authors = ["drklee3 <dlee3@scu.edu>"]

[dependencies]
threadpool = "1.0"
rand = "0.5"
regex = "1.0"
csv = "1.0"
lazy_static = "1.0"
serde = "1.0"
serde_derive = "1.0"
